---

name: Test build

on:
  push:
    branches:
      - 'feature/css-redesign'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          branch: master
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '${{ matrix.node-version }}'
      - name: 'Yarn install, test, build and deploy'
        run: >
          git config --global user.name "${{ secrets.GIT_AUTHOR_NAME }}"

          git config --global user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"

          yarn install

          yarn test

          git clone -b gh-pages --single-branch https://${{ secrets.GITHUB_TOKEN }}@github.com/janbaer/howcani.git deploy

          npx vite build
        env:
          CI: true
